[package]
name = "solana-rust-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.31.1"
anyhow = "1.0.98"
bincode = "2.0.1"
clap = {version = "4.5.40", features = ["derive"]}
dirs = "6.0.0"
solana-client = "2.3.2"
solana-program = "2.3"
solana-sdk = "2.3.1"
